[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solciv = "36bGmrBLBohKsXuo9e7yQGj9n34qFznxTH1Sq5WpSjhE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vitor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
